### ISSUE TITLE
Generating Matrices A and B

### ISSUE THREAD

**Issue by Manojbhadu** [jpjporto/MJLS_Learning#1]
Can you please add the Matlab code which you used for generating system matrices?

**Comment by jpjporto** [comment]
I've uploaded the matlab code. 

The `randdirichlet` function uses the `randgamma` function from the [Lightspeed Toolbox](https://github.com/tminka/lightspeed). That function originally comes from the [HDP-HMM, HDP-SLDS Toolbox](https://homes.cs.washington.edu/~ebfox/software/), so I'm not sure why they didn't use the matlab's default `gamrnd`.

Since we assume we have a discrete-time system, you could also generate the system matrices using `rand` and then scaling A by some factor so all the eigenvalues are inside the unit circle.

**Comment by Manojbhadu** [comment]
Thanks!
